## Imports Age depth models generated by CarboCAT from MAtlab into R ##

#### load packages ####
library(R.matlab)

#### load data ####
scenariosAandBRawData=readMat("scenariosAandBMatlabToR.mat")

dipPosition=5 # choose middle grid point in dip direction
#### write age depth models into a list
scenarioA=list()
for (i in  1:150){
  distFromShore=paste(as.character(i/10)," km", sep="")
  scenarioA[[distFromShore]]=list(time=scenariosAandBRawData$timeA[1,],
                                  height=scenariosAandBRawData$am.spatA[dipPosition,i,], # choose the middle of the 10 transects
                                  distanceToShore=distFromShore)
}
scenarioA$SL=scenariosAandBRawData$SL.ScenarioA[1,]

scenarioB=list()
for (i in  1:150){
  distFromShore=paste(as.character(i/10)," km", sep="")
  scenarioB[[distFromShore]]=list(time=scenariosAandBRawData$timeB[1,],
                                  height=scenariosAandBRawData$am.spatB[dipPosition,i,], # choose the middle of the 10 transects
                                  distanceToShore=distFromShore)
}
scenarioB$SL=scenariosAandBRawData$SL.ScenarioB[1,]

ageDepthModels=list(A=scenarioA,
                    B=scenarioB)

#### save outputs ####
save(ageDepthModels,file="ageDepthModelsScenariosAandB.Rdata")

#### plot some results ####
scenario="A" #"A" or "B"
dist="1.5 km"

plot(x=ageDepthModels[[scenario]][[dist]]$time,
     y=ageDepthModels[[scenario]][[dist]]$height,
     xlab = "Time [Ma]",
     ylab = "Height [m]",
     type = "l",
     main = paste("Scenario ", scenario,", ", dist, " offshore", sep = ""))