## Imports Age depth models generated by CarboCATLite from Matlab into R ##


#### load raw data ####
scenariosA_and_B_raw_data <- R.matlab::readMat("data/matlab_outputs/scenarioA_and_B_matlab_to_R.mat")

#### write age depth models into a list ####
scenarioA <- list()

# select entries corresponding to time time before 2 Ma
rel_ind <- scenariosA_and_B_raw_data$scenarioA.time[1, ] <= 2

# extract data
for (i in 1:nrow(scenariosA_and_B_raw_data$scenarioA.adm.along.dip)) {
  dist_from_shore <- paste(as.character(i / 10), " km", sep = "")
  scenarioA[[dist_from_shore]] <- list(
    time = scenariosA_and_B_raw_data$scenarioA.time[1, ][rel_ind],
    height = scenariosA_and_B_raw_data$scenarioA.adm.along.dip[i, ][rel_ind],
    distanceToShore = dist_from_shore
  )
}
scenarioA$SL <- scenariosA_and_B_raw_data$scenarioA.sea.level[1, ][rel_ind]

## Same for scenario B
scenarioB <- list()

# select entries corresponding to time time before 2.58 Ma
rel_ind <- scenariosA_and_B_raw_data$scenarioA.time[1, ] <= 2.58

# extract data
for (i in 1:nrow(scenariosA_and_B_raw_data$scenarioB.adm.along.dip)) {
  dist_from_shore <- paste(as.character(i / 10), " km", sep = "")
  scenarioB[[dist_from_shore]] <- list(
    time = scenariosA_and_B_raw_data$scenarioB.time[1, ][rel_ind],
    height = scenariosA_and_B_raw_data$scenarioB.adm.along.dip[i, ][rel_ind],
    distanceToShore = dist_from_shore
  )
}
scenarioB$SL <- scenariosA_and_B_raw_data$scenarioA.sea.level[1, ][rel_ind]

# combine scenarios
ageDepthModels <- list(
  A = scenarioA,
  B = scenarioB
)

#### save outputs ####
save(ageDepthModels, file = "data/R_outputs/ageDepthModelsScenariosAandB.Rdata")


#### visual check ####
plot_adm = FALSE
if (plot_adm){
  scenario <- "B" # "A" or "B"
  dist <- "11 km"
  
  plot(
    x = ageDepthModels[[scenario]][[dist]]$time,
    y = ageDepthModels[[scenario]][[dist]]$height,
    xlab = "Time [Ma]",
    ylab = "Height [m]",
    type = "l",
    main = paste("Scenario ", scenario, ", ", dist, " offshore", sep = "")
  )
}
# leave cleaned workspace
remove(ageDepthModels,scenarioA,scenarioB,scenariosA_and_B_raw_data,rel_ind,i,dist_from_shore,plot_adm)