## Imports Age depth models generated by CarboCATLite from Matlab into R, and
## determine completeness & hiatus durations

#### source utility functions ####

source("code/utils.R")

#### load raw data ####
scenariosA_and_B_raw_data <- R.matlab::readMat("data/matlab_outputs/scenarioA_and_B_matlab_to_R.mat")

#### write age depth models into a list ####
scenarioA <- list()

#### Constants ####
time_res_myr = 0.001 # CarboCATList setting
distance_grid_points_km = 0.1
max_dist_from_shore_km = 15
min_dist_from_shore_km  = 0.1

# select entries corresponding to time time before 2 Ma, the maximum time considered in the simulation
rel_ind <- scenariosA_and_B_raw_data$scenarioA.time[1, ] <= 2

# extract data
for (i in seq_len(nrow(scenariosA_and_B_raw_data$scenarioA.adm.along.dip))) {
  dist_from_shore <- paste(as.character(i  * distance_grid_points_km), " km", sep = "")
  scenarioA[[dist_from_shore]] <- list(
    time = scenariosA_and_B_raw_data$scenarioA.time[1, ][rel_ind],
    height = scenariosA_and_B_raw_data$scenarioA.adm.along.dip[i, ][rel_ind],
    distanceToShore = dist_from_shore
  )
}
scenarioA$SL <- scenariosA_and_B_raw_data$scenarioA.sea.level[1, ][rel_ind]

## Same for scenario B
scenarioB <- list()

# select entries corresponding to time time before 2.58 Ma, the maximum time considered in the simulation
rel_ind <- scenariosA_and_B_raw_data$scenarioA.time[1, ] <= 2.58

# extract data
for (i in 1:nrow(scenariosA_and_B_raw_data$scenarioB.adm.along.dip)) {
  dist_from_shore <- paste(as.character(i / 10), " km", sep = "")
  scenarioB[[dist_from_shore]] <- list(
    time = scenariosA_and_B_raw_data$scenarioB.time[1, ][rel_ind],
    height = scenariosA_and_B_raw_data$scenarioB.adm.along.dip[i, ][rel_ind],
    distanceToShore = dist_from_shore
  )
}
scenarioB$SL <- scenariosA_and_B_raw_data$scenarioA.sea.level[1, ][rel_ind]

# combine scenarios
ageDepthModels <- list(
  A = scenarioA,
  B = scenarioB
)

#### Global infor for ADMs ####
scenarioNames <- names(ageDepthModels)

all_dist_raw = seq(from = min_dist_from_shore_km, to = max_dist_from_shore_km, by = distance_grid_points_km)
all_dist = head(names(ageDepthModels[["A"]]),-1)

maxTimes = list() # duration of scenarios respectively in Ma
for (scenario in scenarioNames){
  maxTimes[[scenario]] = max(ageDepthModels[[scenario]][[all_dist[1]]][["time"]])
}


#### Hiatus positions & duration ####
hiatus_list = list()
for (scenario in scenarioNames){
  res_list = list()
  
  for (dista in all_dist){
    adm = ageDepthModels[[scenario]][[dista]]
    hiatus_position = unique(adm$height[duplicated(adm$height)])
    hiat_time = c()
    for (i in  seq_along(hiatus_position)){
      hiat_time[i] = diff(range(adm$time[adm$height == hiatus_position[i]]))
    }
    res_list[[dista]] = list(hiatus_position = hiatus_position,
                             hiatus_duration = hiat_time)
  }
  hiatus_list[[scenario]] = res_list
}

#### statistical measures of hiatus durations ####
hiat_measures = list()
for (scenario in scenarioNames){
  compl = rep(NA, length(all_dist))
  median_duration_myr = rep(NA, length(all_dist))
  first_quartile_duration_myr = rep(NA, length(all_dist))
  third_quartile_duration_myr = rep(NA, length(all_dist))
  max_duration_myr = rep(NA, length(all_dist))
  for (i in seq_along(all_dist)){
    compl[i] = get_completeness(pos = all_dist[i], scenario = scenario)
    hiat_distr = get_hiatus_distribution(pos = all_dist[i], scenario = scenario)
    median_duration_myr[i] = median(hiat_distr)
    first_quartile_duration_myr[i] = quantile(hiat_distr, 0.25)
    third_quartile_duration_myr[i] = quantile(hiat_distr,0.75)
    max_duration_myr[i] = max(hiat_distr)
    
  }
  li = list()
  li[["completeness"]] = compl
  li[["median_duration_myr"]] = median_duration_myr
  li[["first_quartile_duration_myr"]] = first_quartile_duration_myr
  li[["third_quartile_duration_myr"]] = third_quartile_duration_myr
  li[["max_duration_myr"]] = max_duration_myr
  hiat_measures[[scenario]] = li
}



#### save outputs ####
save(ageDepthModels,
     scenarioNames,
     all_dist, 
     all_dist_raw, 
     hiatus_list,
     hiat_measures,
     maxTimes,
     distance_grid_points_km,
     max_dist_from_shore_km,
     min_dist_from_shore_km,
     time_res_myr,
     file = "data/R_outputs/ageDepthModelsScenariosAandB.Rdata")


#### visual check ####
plot_adm = FALSE
if (plot_adm){
  scenario <- "B" # "A" or "B"
  dist <- "11 km"
  
  plot(
    x = ageDepthModels[[scenario]][[dist]]$time,
    y = ageDepthModels[[scenario]][[dist]]$height,
    xlab = "Time [Ma]",
    ylab = "Height [m]",
    type = "l",
    main = paste("Scenario ", scenario, ", ", dist, " offshore", sep = "")
  )
}


